_BASE_: "../../Base-RCNN-C4-OWOD.yaml"
MODEL:
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  WEIGHTS: "/home/fk1/workspace/OWOD/output/t1_std_faster_rcnn/model_final.pth"
#  WEIGHTS: "/home/fk1/workspace/OWOD/output/t1_only_thresh/model_final.pth"
#  WEIGHTS: "/home/fk1/workspace/OWOD/output/t1_clustering_with_save/model_final.pth"
  ROI_HEADS:
    POSITIVE_FRACTION: 0.25
    NMS_THRESH_TEST: 0.5
    SCORE_THRESH_TEST: 0.05
TEST:
  DETECTIONS_PER_IMAGE: 50
DATASETS:
  TRAIN: ('t1_voc_coco_2007_train', ) # t1_voc_coco_2007_train, t1_voc_coco_2007_ft
  TEST: ('voc_coco_2007_test', )   # voc_coco_2007_test
SOLVER:
  STEPS: (12000, 16000)
  MAX_ITER: 18000
  WARMUP_ITERS: 100
OUTPUT_DIR: "./output/t1_test_rerun"
OWOD:
  PREV_INTRODUCED_CLS: 0
  CUR_INTRODUCED_CLS: 20

#    POSITIVE_FRACTION: 0.25
#    NMS_THRESH_TEST: 0.5
#    SCORE_THRESH_TEST: 0.05