_BASE_: "../../Base-RCNN-C4-OWOD.yaml"
MODEL:
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
#  WEIGHTS: "/home/fk1/workspace/OWOD/output/t1_ENABLE_CLUSTERING/model_final.pth"
  WEIGHTS: "/home/fk1/workspace/OWOD/output/t2_ft/model_final.pth"
DATASETS:
  TRAIN: ('t2_voc_coco_2007_train', ) # t1_voc_coco_2007_train, t1_voc_coco_2007_ft
  TEST: ('voc_coco_2007_test', )
TEST:
  DETECTIONS_PER_IMAGE: 50
SOLVER:
  STEPS: (50000, 60000)
  MAX_ITER: 70000
  WARMUP_ITERS: 0
OUTPUT_DIR: "./output/t2_evaluate"
OWOD:
  PREV_INTRODUCED_CLS: 20
  CUR_INTRODUCED_CLS: 20
