_BASE_: "../Base-RCNN-C4-OWOD.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
#  WEIGHTS: "/home/fk1/workspace/OWOD/output/expr_training_with_unk_with_clustering_Z_DIMENSION_256/model_final.pth"
#  WEIGHTS: "/home/fk1/workspace/OWOD/output/t1/model_final.pth"
DATASETS:
  TRAIN: ('voc_2007_trainval', 'voc_2012_trainval', 't2_test_unk')
  TEST: ('voc_2007_test_unk', )
#  TEST: ('t2_all_test_unk', )

#  TEST: ('voc_2007_test','t2_test_unk', 't3_test_unk', 't4_test_unk')
SOLVER:
  STEPS: (12000, 16000)
  MAX_ITER: 18000
  WARMUP_ITERS: 100
OUTPUT_DIR: "./output/expr_training_with_unk_with_clustering_cdist_10"
OWOD:
  PREV_INTRODUCED_CLS: 0
  CUR_INTRODUCED_CLS: 20