_BASE_: "../Base-RCNN-C4-OWOD.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
DATASETS:
  TRAIN: ('t3_train',)
  TEST: ('voc_2007_test','t2_test', 't3_test', 't4_test_unk')
SOLVER:
  STEPS: (32000, 36000)
  MAX_ITER: 38000
  WARMUP_ITERS: 0
OUTPUT_DIR: "./output/t3"
OWOD:
  PREV_INTRODUCED_CLS: 40
  CUR_INTRODUCED_CLS: 20